version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--bind_ip_all"] # Kimlik doğrulama kapalı

  backend:
    build:
      context: ./
    container_name: server-container
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    environment:
      ATLAS_URI: mongodb://mongodb:27017/sample_training # MongoDB bağlantı URI'si
    restart: always

volumes:
  mongo-data:
