version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--bind_ip_all"]

  backend:
    build:
      context: ./server # Backend'in Dockerfile'ının bulunduğu dizin
    container_name: server-container
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    environment:
      ATLAS_URI: mongodb://mongodb:27017/sample_training # MongoDB bağlantı URI'si
    restart: always

  client:
    build:
      context: ./client # Client'in Dockerfile'ının bulunduğu dizin
    container_name: client-container
    ports:
      - "3000:80" # Nginx için 80 portu client için 3000'e yönlendiriliyor
    depends_on:
      - backend # Client, backend'e bağlı
    restart: always

volumes:
  mongo-data:
